version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-bookhub
    environment:
      POSTGRES_DB: bookhub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookhub-network